let eat: Sprite = null
let guy = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 1 . . . . . . 
    . . . . 1 1 1 1 1 1 1 . . . . . 
    . . . 1 f f 1 1 1 f f 1 . . . . 
    . . . 1 f f 1 1 1 f f 1 1 . . . 
    . . 1 1 1 1 1 1 1 1 1 1 1 . . . 
    . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
    . 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    . 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
    `, SpriteKind.Player)
controller.moveSprite(guy, 25, 25)
scene.setBackgroundImage(img`
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbbbbbbebbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbb11111bbbbbbbbbbbbbbbbbbb11111bbbbbbddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbb11111bbbbbbbbbbbbbbbbbbb11111bbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbb11111bbbbbbbbbbbbbbbbbbb11111bbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbb11111bbbbbbbbbbbbbbbbbbb11111bbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddd555dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddd555eeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddd555eeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeddddddddeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeddddddddeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeedddddddddeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeedddddddddeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeedddddddddddddddeeeeeeeeeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeee666666666666eeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeebbbbbbbbbbbbbbbbeeeeeeedddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeebbbbbbbbbbbbbbbbeeeeeeedddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeebbbbbbbbbbbbbbbbeeeeeeedddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeedddddddddddddddddddddddddddddddeeeebbbbbbbbbbbbbbbbeeeeeeedddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeedddddddddddddddddddddddddddddddeeeebbbbbbbbbbbbbbbbeeeeeeedddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666bbbeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666bbbeeeeeddddddddddddddddddddddddddddddddeeeddeeeddddddeeedddeeeddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666bbbeeeeeddddddddddddddddddddddddddddddddeeeddeeeddddddeeedddeeeddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeeddddddddddddddddddddddddddddddddeeedddddddddddddddddeeeddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeeddddddddddddddddddddddddddddddddeeedddddddddddddddddeeeddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeedddddddddddddddddddddddd6666666666eeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddfffffdddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddfffffdddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddfffffdddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddfffffdddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddfffffdddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeee66666eddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    `)
game.onUpdateInterval(5000, function () {
    eat = sprites.create(img`
        . . . . . . . e e e e . . . . . 
        . . . . . e e e e e e . . . . . 
        . . . . . 4 4 4 4 4 . . . . . . 
        . . . . . 4 f 4 f 4 . . . . . . 
        . . . . . 4 4 4 4 4 . . . . . . 
        . . . . 6 6 6 6 6 6 6 . . . . . 
        . . . 6 . 6 6 6 6 6 . 6 . . . . 
        . . 4 . . 6 6 6 6 6 . . 4 . . . 
        . . . . . 6 6 6 6 6 . . . . . . 
        . . . . . 6 6 6 6 6 . . . . . . 
        . . . . . f . . . f . . . . . . 
        . . . . . f . . . f . . . . . . 
        . . . . . f . . . f . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    eat.follow(guy, 10)
    eat.setPosition(11, 13)
})
